baseURL = 'https://burciaga.design/'
languageCode = 'en-us'
title = 'Stephanie Burciaga'
uglyURLs = false
relativeURLs = true
disableKinds = ["sitemap", "RSS", "404", "taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[params]
  Description = "Stephanie Burciaga is a Bay Area graphic designer who specializes in eye-catching editorial layouts, logos, and user interfaces."
  Github = "https://github.com/srciaga"
  Linkedin = "https://linkedin.com/in/srciaga"
  Instagram = "https://www.instagram.com/srciaga/"
